#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Oct 12 09:05:11 2017

@author: Alicia
"""
def powerset(L):
    if len(L)==0:
        return [[]]
    left=L[0:1]
    right=L[1:]
    new=powerset(right)[:]
    for i in powerset(right):
        new.append(i+[left])
    return new
print(powerset([1,2]))